#!/usr/bin/env bash

## Shortcut for importing config only (using config split)
##
## usage: fin imp [pull|full]

cd ${PROJECT_ROOT}
if [[ "$1" = 'full' ]]; then
    echo "*** (0/6) fin up: ***"
    fin up
    echo "(*/6) git pull: "
    git pull
fi
if [[ "$1" = 'pull' ]]; then
    echo "(*/6) git pull: "
    git pull
fi
echo "*** (1/6) composer install: ***"
cd ${PROJECT_ROOT}/${DOCROOT}
# Exception for WWF: Normally this is not executed in docroot.
composer install
echo "*** (2/6) fin drush updb: ***"
fin drush updb
echo "*** (3/6) fin drush cr: ***"
fin drush cr
echo "*** (4/6) fin drush cim: ***"
fin drush cim
echo "*** (5/6) fin drush cr: ***"
fin drush cr
echo "*** (6/6) fin sass: ***"
fin sass
if [[ -z "$1" ]]; then
    echo "you can use 'fin imp pull' to 'git pull' before importing config"
fi