#!/usr/bin/env bash

## Shortcut for compiling ao-canvas in drupal 8
##
## usage: fin cr

cd ${PROJECT_ROOT}/${DOCROOT}/themes/custom/ao-canvas
gulp
cd ${PROJECT_ROOT}/${DOCROOT}/themes/custom/ao-canvas
gulp
